spring.application.name=paymentservice
server.port=8084

spring.liquibase.enabled=false
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml
spring.liquibase.driver-class-name=liquibase.ext.mongodb.database.MongoClientDriver