spring.application.name=paymentservice
server.port=8084

spring.liquibase.enabled=false
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml
spring.liquibase.driver-class-name=liquibase.ext.mongodb.database.MongoClientDriver


random-org.url= https://www.random.org
random-org.num= 1
random-org.min= 1
random-org.max= 1000
random-org.col= 1
random-org.base= 10
random-org.format= plain
random-org.rnd=new